version: '2'
services:
  mdl-db:
    image: 'mariadb:latest'
    container_name: mdl-kramp
    environment:
      - MYSQL_ROOT_PASSWORD=Th0m@s
    volumes:
      - '/home/prod/moodledb_data:/var/lib/mysql'
      
  moodle:
    image: 'bitnami/moodle:3'
    container_name: db-kramp
    environment:
      - MARIADB_HOST=db-kramp
      - MARIADB_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=root
      - MOODLE_DATABASE_PASSWORD=Th0m@s
      - MOODLE_DATABASE_NAME=mdl-db
      - VIRTUAL_HOST=m.test.be
      #- VIRTUAL_PORT=8001
      - LETSENCRYPT_HOST=m.test.be
      - LETSENCRYPT_EMAIL=j@ba.be
      - MOODLE_SKIP_INSTALL=yes 
    volumes: 
      - /home/prod/moodle_data:/bitnami/moodle
    #ports:
    #  - 8001:80

  wp-db:
    image: 'mariadb:latest'
    container_name: db-kramp
    environment:
      - MYSQL_ROOT_PASSWORD=Th0m@s
    volumes:
      - '/home/prod/wpdb_data/:/var/lib/mysql'
  
  wordpress:
    image: 'wordpress:latest'
    container_name: wp-kramp
    environment:
      - WORDPRESS_DB_HOST=db-kramp
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=Th0m@s
      - WORDPRESS_DB_NAME=wp-db 
      - VIRTUAL_HOST=test.be,www.test.be
      - LETSENCRYPT_HOST=test.be,www.test.be
      - LETSENCRYPT_EMAIL="j@ba.be"
      #- VIRTUAL_PORT=8000  
    volumes:
      - '/home/prod/wp_data:/var/www/html'
    #ports: 
    #  - 8000:80
    depends_on:
      - wpdb      
  
           
#volumes:
 # mariadb_data:
 #   driver: local
 # moodle_data:
 #   driver: local
 # wpdb_data:
 #   driver: local 
 # wp_data:
 #   driver: local 
