version: '2'
services:
  moodleDB:
    image: 'mariadb:latest'
    container_name: moodleDB
    environment:
      - MYSQL_ROOT_PASSWORD=Th0m@s
      - MYSQL_DATABASE=moodleDB
    volumes:
      - '/data/moodle/moodleDB:/var/lib/mysql'
    networks:
      - moodleNet
      
  moodle:
    image: 'bitnami/moodle:3'
    container_name: moodle
    environment:
      - MARIADB_HOST=moodleDB
      - MARIADB_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=root
      - MOODLE_DATABASE_PASSWORD=Th0m@s
      - MOODLE_DATABASE_NAME=moodleDB
      - VIRTUAL_HOST=m.test.be
      - LETSENCRYPT_HOST=m.test.be
      - LETSENCRYPT_EMAIL=j@ba.be
      - MOODLE_SKIP_INSTALL=yes 
    volumes: 
      - /data/moodle/moodle:/bitnami/moodle
    networks:
      - moodleNet
    depends_on:
      - moodleDB

  wordpressDB:
    image: 'mariadb:latest'
    container_name: wordpressDB
    environment:
      - MYSQL_ROOT_PASSWORD=Th0m@s
      - MYSQL_DATABASE=wordpressDB
    volumes:
      - '/home/wordpress/wordpressDB/:/var/lib/mysql'
    networks:
      - wordpressNet
  
  wordpress:
    image: 'wordpress:latest'
    container_name: wordpress
    environment:
      - WORDPRESS_DB_HOST=wordpressDB
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=Th0m@s
      - WORDPRESS_DB_NAME=wordpressDB 
      - VIRTUAL_HOST=test.be,www.test.be
      - LETSENCRYPT_HOST=test.be,www.test.be
      - LETSENCRYPT_EMAIL="j@ba.be"
      #- VIRTUAL_PORT=8080  
    volumes:
      - '/home/wordpress/wordpress:/var/www/html'
    #ports: 
      #- 127.0.0.1:8080:80
    networks:
      - wordpressNet
    depends_on:
      - wordpressDB 

networks:
  moodleNet:
    driver: moodleDriver
  wordpressNet:
    driver: wordpressDriver
    
volumes:
  moodleDB:
    driver: local
  moodle:
    driver: local
  wordpressDB:
    driver: local 
  wordpress:
    driver: local 