version: '2'
services:
  moodleDB:
    image: 'bitnami/mariadb:latest'
    container_name: moodleDB
    environment:
      - MARIADB_USER=root
      - MARIADB_PASSWORD=root
      - MARIADB_DATABASE=moodleDB
      - MARIADB_ROOT_PASSWORD=root
      - VIRTUAL_PORT=3306
    volumes:
      - '/data/moodle/moodleDB:/bitnami/mariadb'
    ports:
      - 127.0.0.1:3306:3306
    networks:
      - moodleNet
      
  moodle:
    image: 'bitnami/moodle:3'
    container_name: moodle
    environment:
      - MOODLE_DATABASE_USER=root
      - MOODLE_DATABASE_PASSWORD=root
      - MOODLE_DATABASE_NAME=moodleDB
      - MOODLE_DATABASE_HOST=moodleDB
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - VIRTUAL_PORT=8000
    volumes: 
      - /data/moodle/moodle:/bitnami/moodle
    ports:
      - 127.0.0.1:8000:80
    networks:
      - moodleNet
    depends_on:
      - moodleDB

  # wordpressDB:
  #   image: 'mariadb:latest'
  #   container_name: wordpressDB
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=Th0m@s
  #     - MYSQL_DATABASE=wordpressDB
  #   volumes:
  #     - '/home/wordpress/wordpressDB:/var/lib/mysql'
  #   networks:
  #     - wordpressNet
  
  # wordpress:
  #   image: 'wordpress:latest'
  #   container_name: wordpress
  #   environment:
  #     - WORDPRESS_DB_HOST=wordpressDB
  #     - WORDPRESS_DB_USER=root
  #     - WORDPRESS_DB_PASSWORD=Th0m@s
  #     - WORDPRESS_DB_NAME=wordpressDB
  #     - VIRTUAL_PORT=8080  
  #   volumes:
  #     - '/home/wordpress/wordpress:/var/www/html'
  #   ports: 
  #     - 127.0.0.1:8080:80
  #   networks:
  #     - wordpressNet
  #   depends_on:
  #     - wordpressDB 

networks:
  moodleNet:
    driver: bridge
  # wordpressNet:
  #   driver: bridge
    
volumes:
  moodleDB:
    driver: local
  moodle:
    driver: local
  # wordpressDB:
  #   driver: local 
  # wordpress:
  #   driver: local 