---
 - hosts: all
   become: yes
   vars:
    data_path: /data

   tasks:
   - name: Update apt cache
     apt: 
       update_cache: yes

   - name: Install Check_MK
     docker_container:
      name: checkMon
      image: checkmk/check-mk-raw:1.5.0-latest
      volumes:
      - "{{ data_path }}:/omd/sites"
      - /etc/localtime:/etc/localtime:ro
      ports:
       - 8081:5000
      
   - name: Extract cmk.tar.gz into /data/cmk
     ansible.builtin.unarchive:
       src: "~/Documents/files/checkmk/cmk.tar.gz"
       dest: "{{ data_path }}"
       
   - name: Stop Check-MK
     docker_container:
       name: checkMon
       state: stopped
       
   - name: Start Check-MK
     docker_container:
       name: checkMon
       state: started  
       
     
