version: '2'
services:
  jenkins:
    image: jenkins/jenkins:latest
    container_name: composeJenkins
    volumes:
      - "data/compose/jenkins:/var/jenkins_home"
    ports:
      - "8080:80"

volumes:
  jenkins:
    driver: local