---
 - hosts: all
   become: yes
   # ansible-galaxy collection install community.general
   # community.general.ufw

   tasks:
   - name: Update apt cache
     apt: 
       update_cache: yes

   # curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.6.2-amd64.deb
   - name: Copy filebeat
     copy:
       src: "~/Documents/Repo/pong/pipeline/plugins/filebeat-7.6.2-amd64.deb"
       dest: "/home/{{ ansible_user }}/Documents/"
       owner: "{{ ansible_user }}"
       group: root        
       mode: 0755

   # sudo dpkg -i filebeat-7.6.2-amd64.deb
   - name: Install filebeat
     apt:
       deb: "/home/{{ ansible_user }}/Documents/Repo/pong/pipeline/plugins/filebeat-7.6.2-amd64.deb"

   - name: Go to /etc/filebeat/
     chdir: /etc/filebeat/
       
   #- name: Restart filebeat
   #  ansible.builtin.systemd:
   #    state: restarted
   #    name: filebeat.service
