---
 - hosts: all
   become: yes

   tasks:
   - name: Update apt cache
     apt: 
       update_cache: yes
   
   - name: Clone git repo with files
     ansible.builtin.git:
       repo: "https://github.com/ThomasKramp/DevOpsLabo.git"
       dest: "/home/{{ ansible_user }}/Documents"


