---
 - hosts: all
   become: yes

   tasks:
   - name: Update apt cache
     apt: 
       update_cache: yes
       
   - name: Create Container
     docker_container:
      name: pong
      image: 
      volumes:
       - "{{ data_path }}pong:/usr/local/apache2/htdocs/"
      ports:
       - "8082:80"
       
docker run -dit --name pong -p 8082:80 -v /data/pong:/usr/local/apache2/htdocs/ httpd:2.4
# usr/local/apache2/htdocs/

# https://medium.com/appgambit/ansible-playbook-with-jenkins-pipeline-2846d4442a31
# https://stackoverflow.com/questions/63847775/ansible-playbook-fails-when-executed-through-jenkins-usr-bin-env-python3-n
