---
 - hosts: all
   # ansible-playbook kramp.yml
   # ssh-keygen
   # cat ~/.ssh/id_rsa.pub
   # ssh-copy-id kramp@192.168.0.50
   # sudo tar -xvf ~/Documents/jenkins.tar.gz -C /data
   
   vars:
    data_path: /data
    git_user: ThomasKramp
    git_mail: s115472@ap.be
    wp_pw: root
    wp_db: wpdb
    
   become: yes

   tasks:
   - name: Update apt cache
     apt: 
       update_cache: yes
   
   - name: copying file with playbook
     become: true 
     copy:
       src: ~/Documents/files/jenkins.tar.gz
       dest: "/home/{{ ansible_user }}/Documents/"
       owner: "{{ ansible_user }}"
       group: root        
       mode: 0755

   - name: Install Jenkins
     docker_container:
      name: jenkins
      image: jenkins/jenkins:latest
      volumes:
       - "{{ data_path }}/jenkins:/var/jenkins_home"
      ports:
       - "8080:80"

   - name: Enable Jenkins
     command: "chmod a+rw {{ data_path }}/jenkins"
     args:
      warn: false
      
   - name: copying file with playbook
     become: true 
     copy:
       src: ~/Documents/files/jenkins.tar.gz
       dest: "/home/{{ ansible_user }}/Documents/"
       owner: "{{ ansible_user }}"
       group: root        
       mode: 0755
      
   - name: Extract foo.tgz into /var/lib/foo
     ansible.builtin.unarchive:
       src: "~/Documents/files/jenkins.tar.gz"
       dest: "{{ data_path }}"
      
