---
 - hosts: all
   # ansible-playbook tar.yml
   # ssh-keygen
   # cat ~/.ssh/id_rsa.pub
   # ssh-copy-id kramp@192.168.0.50
   
   # sudo tar -zcvf jenkins.tar.gz jenkins/
   # cp -r jenkins.tar.gz ~/Documents/Repo/pong/

   become: yes

   tasks:
   - name: Update apt cache
     apt: 
       update_cache: yes

   - name: copying file with playbook
     become: true 
     copy:
       src: ~/Documents/files/jenkins.tar.gz
       dest: "/home/{{ ansible_user }}/Documents/"
       owner: "{{ ansible_user }}"
       group: root        
       mode: 0755
