---
 - hosts: all
   become: yes
   # https://graspingtech.com/install-docker-ansible/
   
   tasks:
   - name: Update apt cache
     apt: 
       update_cache: yes
   
   - name: Install dependencies
     apt: 
       name: "{{ item }}"
       state: latest
       update_cache: yes
     loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'gnupg-agent', 'python3-pip', 'python3-setuptools' ]
     
   - name: Add an apt signing key for Docker
     apt_key:
       url: https://download.docker.com/linux/ubuntu/gpg
       state: present

   - name: Add Docker Repository
     apt_repository:
       repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
       state: present
   
   - name: Install Docker
     apt: 
       name: "docker-ce"
       state: latest
       update_cache: yes
     #loop: [ 'docker-ce', 'docker-ce-cli', 'containerd.io']
     
   - name: install certain python modules for docker
     pip:
       name: "{{ item.name }}"
       state: present
     loop:
       - { name: docker }
       - { name: docker-py }

   - name: Add user to docker group
     user:
       name: "{{ansible_user}}"
       group: docker


